"""Integration tests for PyInstaller build pipeline."""

from __future__ import annotations

import pathlib
import sys
from unittest.mock import patch

import pytest

PROJECT_ROOT = pathlib.Path(__file__).parent.parent.resolve()
BUILD_SCRIPT = PROJECT_ROOT / "tools" / "build.py"
ASSETS_DIR = PROJECT_ROOT / "assets"
ICONS_DIR = ASSETS_DIR / "icons"
STAGED_ENGINE = PROJECT_ROOT / "build" / "engine-cpu"


class TestBuildPipeline:
    """Tests against tools/build.py, the canonical builder.

    (WhisperKey.spec is auto-regenerated by PyInstaller on each build, so it is
    a build artifact, not a source of truth.)
    """

    def test_build_script_exists(self) -> None:
        assert BUILD_SCRIPT.exists(), "tools/build.py not found"

    def test_bundles_engine_and_assets(self) -> None:
        content = BUILD_SCRIPT.read_text(encoding="utf-8")
        assert "assets/bin" in content
        assert "assets/icons" in content

    def test_uses_whisper_cpp_v192(self) -> None:
        content = BUILD_SCRIPT.read_text(encoding="utf-8")
        assert "v1.9.2" in content
        assert "whisper-bin-x64.zip" in content

    def test_includes_hidden_imports(self) -> None:
        content = BUILD_SCRIPT.read_text(encoding="utf-8")
        for module in (
            "whisperkey.platform.windows",
            "whisperkey.engine",
            "whisperkey.splash",
            "whisperkey.settings_gui",
            "whisperkey.updater",
        ):
            assert module in content, f"{module} missing from build hidden imports"

    def test_excludes_torch_bloat(self) -> None:
        """Regression guard: torch must be excluded (it bundled 3.5 GB before)."""
        content = BUILD_SCRIPT.read_text(encoding="utf-8")
        assert '"torch"' in content

    def test_references_app_icon(self) -> None:
        content = BUILD_SCRIPT.read_text(encoding="utf-8")
        assert "app.ico" in content


class TestStagedEngine:
    """Tests for the CPU engine staged by build.py (if a build has run)."""

    @pytest.mark.skipif(
        not STAGED_ENGINE.exists(),
        reason="engine not staged — run tools/build.py first",
    )
    def test_server_exe_staged(self) -> None:
        assert any(STAGED_ENGINE.rglob("whisper-server.exe")), "whisper-server.exe not staged"

    @pytest.mark.skipif(
        not STAGED_ENGINE.exists(),
        reason="engine not staged — run tools/build.py first",
    )
    def test_whisper_dll_staged(self) -> None:
        assert any(STAGED_ENGINE.rglob("whisper.dll")), "whisper.dll not staged"

    @pytest.mark.skipif(
        not STAGED_ENGINE.exists(),
        reason="engine not staged — run tools/build.py first",
    )
    def test_example_tools_trimmed(self) -> None:
        """Unused example binaries must be trimmed from the bundle."""
        for junk in ("SDL2.dll", "whisper-stream.exe", "whisper-talk-llama.exe"):
            assert not any(STAGED_ENGINE.rglob(junk)), f"{junk} should have been trimmed"


class TestAssets:
    """Tests for asset inclusion."""

    def test_logo_exists(self) -> None:
        """Verify logo.png exists."""
        logo = ASSETS_DIR / "logo.png"
        assert logo.exists(), "logo.png not found in assets/"
        assert logo.stat().st_size > 0

    def test_tray_icons_exist(self) -> None:
        """Verify tray icons exist."""
        assert ICONS_DIR.exists(), "assets/icons/ directory not found"

        required_icons = [
            "tray_idle.png",
            "tray_ready.png",
            "tray_loading.png",
            "tray_error.png",
        ]

        for icon in required_icons:
            icon_path = ICONS_DIR / icon
            assert icon_path.exists(), f"{icon} not found in assets/icons/"
            assert icon_path.stat().st_size > 0, f"{icon} is empty"

    def test_app_icon_exists(self) -> None:
        """Verify app.ico exists."""
        app_ico = ICONS_DIR / "app.ico"
        assert app_ico.exists(), "app.ico not found in assets/icons/"
        assert app_ico.stat().st_size > 0


class TestE2EWhisperCpp:
    """E2E tests for whisper.cpp execution (requires manual testing)."""

    @pytest.mark.skip(reason="Requires manual E2E testing with installed app")
    def test_installed_app_can_execute_whisper_cpp(self) -> None:
        """Verify installed app can execute whisper.cpp.

        Manual test steps:
        1. Build installer with `installer/build.bat`
        2. Install WhisperKey-Setup.exe
        3. Launch installed app
        4. Verify transcription works
        """

    @pytest.mark.skip(reason="Requires manual E2E testing")
    def test_installed_app_preserves_config(self) -> None:
        """Verify installed app preserves config after reinstall.

        Manual test steps:
        1. Install WhisperKey
        2. Configure custom settings
        3. Uninstall (preserve config)
        4. Reinstall
        5. Verify settings preserved
        """
